### ISSUE TITLE
Can tape-watch work with ES6?

### ISSUE THREAD

**Issue by jonahx** [rstacruz/tape-watch#15]
UPDATE: After posting this, I realize it's just an ES6 issue, so my questions is now just: How can I get tape-watch to work with ES6?

Thanks,
Jonah

**Comment by evgenykochetkov** [comment]
You can start tape-watch with [babel-node](https://babeljs.io/docs/usage/cli/)
For example, `babel-node tape-watch ./tests/**/*.js`

**Comment by rstacruz** [comment]
^- yep. or you can use [babel-register](https://www.npmjs.com/package/babel-register) as part of your test suite invocation.

**Comment by queckezz** [comment]
Just wanted to chime in to say that @evgenykochetkov command is not working for me. For anybody else that has this problem: I had to actually reference the *original* `.bin/tape-watch`:

```bash
babel-node node_modules/tape-watch/bin/tape-watch test/index.js
```

`./node_modules/.bin/tape-watch` is actually wrapped in some wierd additional bash setup and of course is failing with babel. 

Thanks for the tip with `babel-node` though! It's a lot faster than spinning up `babel-register` (on each change) on my slow corporate machine

**Comment by jonahx** [comment]
Just wanted to add that I was able to get @queckezz method working without babel-node, just like this:

    node --harmony --harmony-destructuring node_modules/tape-watch/bin/tape-watch

**Comment by rstacruz** [comment]
I'll be adding babel support in 2.0.

**Comment by rstacruz** [comment]
For 2.0, you can now do:

```
tape-watch -r babel-register test.js
```

**Comment by brunoreis** [comment]
If you are using babel 7 the package is @babel/register instead of babel-register, so use: 

`tape-watch -r @babel/register`
