### ISSUE TITLE
Allow shell for -o option to be specified

### ISSUE THREAD

**Issue by jonahx** [rstacruz/tape-watch#17]
Because the `-o` defaults to using `/bin/sh`, and you cannot to my knowledge change this, it breaks certain useful bashisms.  For example, I'm trying to do:

    tape-watch -o '| tee >(./tape-growl.js) | faucet' test.js

but `/bin/sh` does not support command substitutions like this.

**Comment by rstacruz** [comment]
That's a really interesting case, perhaps you can do:

```
tape-watch -o '| bash -c "tee >(./tape-growl.js)" | faucet' test.js
```

tape-watch doesn't actually use `/bin/sh`, rather it splits your input along `|` characters and uses `require('child_process').exec` directly on each piece. See [outpipe's source](https://github.com/substack/outpipe/blob/master/index.js).

Closing this as this seems like needless complexity that can be worked around with. If anyone would like to implement an implementation to `outpipe` with this functionality, let me know and I'll take a look.

Thanks for the report!

**Comment by jonahx** [comment]
Thanks!  Your suggestion worked beautifully.
