### ISSUE TITLE
info: module for using growl with tape-watch

### ISSUE THREAD

**Issue by jonahx** [rstacruz/tape-watch#18]
rico,

i've been using tape-watch in my workflow a lot, and wanted to integrate growl notifications.  once i got it working, i decided to publish it as an npm module: https://www.npmjs.com/package/tape-growl.

also, it's my first ever npm module, so if you have any feedback i'd appreciate it.  thanks for tape-watch.

**Comment by rstacruz** [comment]
nice work!

**Comment by rstacruz** [comment]
Let me add it in the readme.
