### ISSUE TITLE
tape-watch tries to run tests before globstar names are resolved

### ISSUE THREAD

**Issue by ratiotile** [rstacruz/tape-watch#51]
Latest versions installed.
"tape": "^4.6.0"
"tape-watch": "~2.1.0"

I have tape-watch installed locally, but I also tried with it installed globally. This doesn't find any tests.
```
node_modules/tape-watch/bin/tape-watch -r babel-register 'src/**/test_*'
TAP version 13

1..0
# tests 0
# pass  0

# ok

```
But tape by itself will find the test.
```
node_modules/tape/bin/tape -r babel-register 'src/**/test_*'
TAP version 13
# test
ok 1 should be truthy

1..1
# tests 1
# pass  1

# ok
```
What is going on here?

**Comment by ratiotile** [comment]
It appears that globstar file lookup is broken.
`tape-watch test.js` works, and
`tape-watch */test.js` works, but
`tape-watch src/**/test.js` appears to do the same thing as `tape-watch src/*/test.js` and only looks 1 dir deep instead of in all recursive directories.

**Comment by pke** [comment]
I have a similar problem:

this does *not* work:

`tape-watch -r babel-register ./specs/index.js './src/**/*.spec.jsx' -p faucet`

this does work:

`tape -r babel-register ./specs/index.js './src/**/*.spec.jsx' | faucet`

**Comment by nicosommi** [comment]
@pke and @ratiotile 
Meanwhile, this do the same thing but using the watch package (with my chosen reporter and paths)
watch 'tape -r babel-register 'tests/**/*.js' | tap-spec' 'tests' --interval=0.01

**Comment by rstacruz** [comment]
Thanks for the reports. Pull requests are welcome!

**Comment by pke** [comment]
@nicosommi how does the `watch` package which files to watch?

**Comment by nicosommi** [comment]
@pke the whole 'tests' directory in my case, the default is the current work dir

**Comment by pke** [comment]
@nicosommi Ah now I see the second to last argument :)

**Comment by ratiotile** [comment]
I've debugged a bit, and it looks like the glob-star is expanded properly, and all the filenames are output as being required... the test files don't get executed however.

**Comment by ratiotile** [comment]
The problem is that when a globstar filename is given, the execution of the tests happens before they are required.

When a single file is specified, it is required before the tape executes.
```
tape-watch start +0ms [ undefined ]
  tape-watch filenames: +21ms [ 'fixtures/src/test/test_jsx.jsx' ]
  tape-watch requiring +16ms fixtures/src/test/test_jsx.jsx
TAP version 13
# ran test/test.jsx
ok 1 works
  tape-watch tape finished +7ms

1..1
# tests 1
# pass  1

# ok
  tape-watch done +1ms
  tape-watch listening again +251ms

```
When globstar is used, tape executes before the filenames are processed.
```
tape-watch start +0ms [ undefined ]
  tape-watch filenames: +21ms [ 'fixtures/**/*.@(js|jsx|es6)' ]
TAP version 13
  tape-watch tape finished +16ms

1..0
# tests 0
# pass  0

# ok
  tape-watch done +3ms
  tape-watch requiring +14ms fixtures/othertest.js
  tape-watch requiring +3ms fixtures/src/test/a/test_es6.es6
  tape-watch requiring +1ms fixtures/src/test/b/test_js.js
  tape-watch requiring +1ms fixtures/src/test/test_jsx.jsx
  tape-watch listening again +234ms

```

**Comment by rstacruz** [comment]
tape-watch v2.2.2 is out and this is probably fixed. Thanks for the reports, and please leave a note if it persists!

**Comment by ratiotile** [comment]
I just got around to testing the official release of tape-watch again, and v2.2.3 still fails to find any of my tests. Please take another look at my pull request #55 which has been working for me.
