### ISSUE TITLE
What's up with `once`?

### ISSUE THREAD

**Issue by tuckerconnelly** [rstacruz/tape-watch#53]
I want it :X Looks like you added it and removed it? It's still in the docs.

I want it so I can run the same command for running tests in CI as I do for watching in development.

**Comment by rstacruz** [comment]
It's the same as tape's executable haha

**Comment by tuckerconnelly** [comment]
Haha gotcha. Would still like it so I don't have to make another command :) With `-1` I can do:

`npm test -- -1`

**Comment by rstacruz** [comment]
Oh that's a good point. Sure lets bring it back.

**Comment by rstacruz** [comment]
2.2.0 is out now with support for `-1`. There's also support for `--watch`, which cancels out `-1`.

You can now add this to your `package.json`:

```js
  "scripts": {
    "test": "tape-watch -1 test/*"
  }
```

You can now run tests with `npm test`, or make it auto-run with `npm test -- --watch`. Thanks @tuckerconnelly!

**Comment by tuckerconnelly** [comment]
@rstacruz LEGEND
